# (optional)
name = "maximum_configuration"
# remove cargo plugin in order to manually configure everything
disabled_plugins = ["cargo"]


# OPTION 1: declare "workspace/project" wide dependencies, usefull when they are reused
# [dependencies.foo_lib]
# kind = "Runtime"
# provides = ["libfoo_lib.so", "foo_lib.dll", "foo_lib.dylib"]

# [targets.maximum_configuration]
# dependencies = ["foo_dylib"]


# OPTION 2: declare dependencies inline
[targets.maximum_configuration]
# TODO: what to do about the profile here?
filepath = "../../target/debug/maximum_configuration"
dependencies = [
	{ name = "foo_lib", kind = "Runtime", provides = ["libfoo_lib.so", "foo_lib.dll", "foo_lib.dylib"] }
]
